### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by jhgravelle** [ziebelje/sqlbee#13]
I can't seem to get past the following error when running setup.php

{"code":0,"message":"cURL error: SSL certificate problem: unable to get local issuer certificate","file":"C:\\wamp64\\www\\sqlbee\\sqlbee.php","line":107,"backtrace":[{"file":"C:\\wamp64\\www\\sqlbee\\sqlbee.php","line":155,"function":"ecobee","class":"sqlbee\\sqlbee","type":"->","args":["GET","authorize",{"response_type":"ecobeePin","scope":"smartRead"}]},{"file":"C:\\wamp64\\www\\sqlbee\\setup.php","line":7,"function":"authorize","class":"sqlbee\\sqlbee","type":"->","args":[]}]}

I'm using WAMP Server, and followed the directions from here https://articlebin.michaelmilette.com/how-to-add-ssl-https-to-wampserver/, and I can get to https://localhost/
I did have to provide an exception in firefox to allow the self signed cert.

Any help would be appreciated, but I understand if you are unable to.

**Comment by ziebelje** [comment]
I believe you need to configure the CA on your server:

http://promincproductions.com/blog/how-to-fix-ssl-certificate-problem-unable-to-get-local-issuer-certificate/
or
https://stackoverflow.com/a/32095378

Your own SSL certificate should be fine otherwise.

**Comment by ziebelje** [comment]
Closing as not related to sqlbee. Suggestions given above for local server configuration.
