### ISSUE TITLE
sqlbee errors

### ISSUE THREAD

**Issue by sandeen** [ziebelje/sqlbee#14]
As requested, reporting runtime errors.  Happy to do any debugging that may be helpful.

```
"code":8,"message":"Undefined index: rs:100","file":"\/src\/git\/sqlbee\/sqlbee.php","line":709
"code":0,"message":"Processing error. startInterval\/endInterval must be between 0 and 287 (5 minute intervals in a day)
"code":2,"message":"Invalid argument supplied for foreach()","file":"\/opt\/sqlbee\/sqlbee.php","line":262
```

https://gist.github.com/sandeen/b42802f38385fa43fbc995f4fc6aa6be#file-gistfile1-txt

**Comment by ziebelje** [comment]
Unable to reproduce.

**Comment by sandeen** [comment]
I dropped the database, updated git from 9d1b0a51db5ec15c7e74ef813d450c98e90c65e0 to current, pulled everything from the API again and now it seems fine.  *shrug*

**Comment by ziebelje** [comment]
Slight panic attack getting an email starting with "I dropped the database".

Anyways, glad it's working! :)

**Comment by sandeen** [comment]
Heh, sorry!
