### ISSUE TITLE
Could not grant token

### ISSUE THREAD

**Issue by apratsunrthd** [ziebelje/sqlbee#15]
Looking at my tables for the first time in a while and realized I'm getting "Could not grant token" since 2019-02-14. I've done everything I know to do including completely removing and recreating the apps at ecobee.com and re-running setup. When I try to run setup and put the new PIN in, I'll get a "Success" and it'll act like it's syncing but it just hangs after cycling through a couple of date ranges.

**Comment by ziebelje** [comment]
You might have just gotten really unlucky. Ecobee was [performing maintenance](https://status.ecobee.com/) this morning until 6am this morning. Not sure exactly when you tried, but that could factor in.

If you try re-running setup again now does it work?

**Comment by apratsunrthd** [comment]
Nope. Just tried it again. Same symptoms.

**Comment by nlighteneddesign** [comment]
Ecobee is also not showing up on home assistant, I think it relies on this as well.

**Comment by apratsunrthd** [comment]
Well, it just decided to start working fine when I tried it again this morning. Closing.
