### ISSUE TITLE
API format appears to have changed

### ISSUE THREAD

**Issue by netbymatt** [ziebelje/sqlbee#16]
The latest 15 minutes or so of data typically report all null values for the thermostat runtime. I don't have an older copy of an API response to compare with, but I traced the problem down to this line. The data manipulation here for a completely null row only generates 29 values to insert instead of 30 on a row with data.
https://github.com/ziebelje/sqlbee/blob/9d1b0a51db5ec15c7e74ef813d450c98e90c65e0/sqlbee.php#L655-L658
I don't have an older copy of an API response to compare with but it seems like there's a trailing comma that isn't present on the null rows. I implemented the following dirty fix for now. With an older copy of an API response it someone could make a more robust solution.
```php
      $row = substr($row, 0, -1); // Strip the trailing comma from the array.
      $row = explode(',', $row);
      // dirty fix for entirely blank rows missing trailing value
      if (sizeof($row) === 29) $row[] = "";
      $row = array_map('trim', $row);
      $row = array_map(array($this->mysqli, 'real_escape_string'), $row);
```
```runtime_report_sensor``` uses similar code but does not appear to be affected.

Edit: I started seeing this error on 7-16-2020.

**Comment by ziebelje** [comment]
It's because the ecobee API is no longer including a trailing comma. When there is a comma at the end of a line instead of a value, that comma is getting killed instead of the value just getting truncated or removed.
