### ISSUE TITLE
Handle timezones

### ISSUE THREAD

**Issue by ziebelje** [ziebelje/sqlbee#3]
Investigate database and PHP date_default_timezone_set

**Comment by senorshaun** [comment]
This uses PHP's timezone which default is the system timezone. PHP 5.1.0 on throws warnings if php is still set to use the systems timezone rather than a hardcoded one. I just set the timezone in my php.ini file and no longer got the errors. This should be done anyways for other php uses

**Comment by ziebelje** [comment]
This is a non-issue. Adding date_default_timezone_set to the script (UTC) to play it safe in a commit shortly. All data sent and received from the Ecobee API at this point is in UTC. The timestamp column in MySQL is stored internally as UTC and returned in whatever time zone you have your database set to. It is up to the database administrator to know how their database and timezone columns are set up.
