### ISSUE TITLE
[REQUEST] Is there a way to pull info from individual sensors?

### ISSUE THREAD

**Issue by senorshaun** [ziebelje/sqlbee#7]
I would like to see the temp, humidity, and occupied from each remote sensor. Does the API surface that information?

**Comment by ziebelje** [comment]
There is an `includeSensors` parameter on the API call that gets runtime report data. I've never explored it since that data isn't quite as useful to me. I'll try it out soon and see what it would take to add that in.

**Comment by bob109** [comment]
Check out json_remote_sensors in the thermostat table.  I'm seeing this json on mine. 
[
  {
    "id": "rs:100",
    "name": "Living Room",
    "type": "ecobee3_remote_sensor",
    "code": "CVCR",
    "inUse": true,
    "capability": [
      {
        "id": "1",
        "type": "temperature",
        "value": "712"
      },
      {
        "id": "2",
        "type": "occupancy",
        "value": "false"
      }
    ]
  },
  {
    "id": "ei:0",
    "name": "Dining Room",
    "type": "thermostat",
    "inUse": true,
    "capability": [
      {
        "id": "1",
        "type": "temperature",
        "value": "679"
      },
      {
        "id": "2",
        "type": "humidity",
        "value": "12"
      },
      {
        "id": "3",
        "type": "occupancy",
        "value": "false"
      }
    ]
  }
]

**Comment by ziebelje** [comment]
The data @bob109 suggested will give you the most recent sensor data and that's already set up and working. It is possible to get historical sensor data as well; I just read up on and tested that. This is something I would be fine with adding but it might be a couple weeks before I can get to it. Parsing the data looks fairly easy but I'd probably want to add a `sensor` table and properly link everything.

**Comment by bob109** [comment]
I should have mentioned that only the latest sensor data is in the thermostat table. 
What I've been doing is querying the mariadb, parsing the json, and poking it into a RRD database to make the pretty graphs.  Kinda round about but it works for my use. Having said that, an all-in-one solution would be the way to go.

**Comment by ziebelje** [comment]
I didn't build any graphing/reporting into this project on purpose because I intended on doing that in a more complete "home automation" library that I was working on.

Here are a couple screenshots of a UI I built for ecobee control and reporting:
https://imgur.com/uIqTUoe
https://imgur.com/j5kWWAH

I haven't touched that project in a while but I'd love to come back to it if I can find the time. All the code is in my [otto](https://github.com/ziebelje/otto) project.

**Comment by starblazr** [comment]
new installation, I'd like to add my 'ping' to adding this to the current branch.  It didn't grab my remote sensors on install..

**Comment by ziebelje** [comment]
Note that *current* sensor data is available already in the thermostat table. Historical data is still not available. Given that's the only outstanding item, maybe I'll get that added. :)

**Comment by starblazr** [comment]
Yeah, historical is what I was looking for.... considering we're logging it :-)

Additionally, I'm working on a commit to streamline setup.php for those who don't read README.md, such as a fail for curl/mysql and creating the database structure in a one-stop-shop.

**Comment by ziebelje** [comment]
This is finally done. :) If you're already using sqlbee, the easiest way to upgrade to this change is to drop all but the `token` table and then create everything again using `sqlbee.sql`. The next time the cron job runs it will automatically re-sync all of your historical thermostat and sensor data. Alternatively you could just follow the full setup instructions from scratch if you want.
